"""make transaction employee_id nullable

Revision ID: 311b9acc4e52
Revises: a64f99e257fc
Create Date: 2026-08-23 05:29:04.918917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311b9acc4e52'
down_revision = 'a64f99e257fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'employee_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'employee_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
