"""add merchant_settlements table

Revision ID: 468f26d7f9c0
Revises: ce7c5746998f
Create Date: 2026-09-01 23:44:36.222928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468f26d7f9c0'
down_revision = 'ce7c5746998f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='merchantsettlementstatus'), nullable=False),
    sa.Column('paid_reference', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'period_year', 'period_month', name='uq_merchant_settlement_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchant_settlements')
    # ### end Alembic commands ###
