"""add transaction location distance

Revision ID: 794ee3c6206a
Revises: ff47a484e6bc
Create Date: 2026-09-10 04:58:32.120569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794ee3c6206a'
down_revision = 'ff47a484e6bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('location_distance_meters', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'location_distance_meters')
    # ### end Alembic commands ###
