"""add transaction resolution note

Revision ID: c3fcff04ff74
Revises: efcd9fd7faf4
Create Date: 2026-09-10 02:07:34.099750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fcff04ff74'
down_revision = 'efcd9fd7faf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('dispute_outcome', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('resolution_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'resolution_note')
    op.drop_column('transactions', 'dispute_outcome')
    # ### end Alembic commands ###
