"""add user profile_photo_filename

Revision ID: ce7c5746998f
Revises: 9bf266430f03
Create Date: 2026-08-27 22:57:12.823207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7c5746998f'
down_revision = '9bf266430f03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo_filename')
    # ### end Alembic commands ###
