"""add merchant postcode

Revision ID: dd4de3f6e98f
Revises: fe814ecfe4ce
Create Date: 2026-09-12 06:15:06.261468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4de3f6e98f'
down_revision = 'fe814ecfe4ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('postcode', sa.String(), nullable=True))
    op.create_index(op.f('ix_merchants_postcode'), 'merchants', ['postcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchants_postcode'), table_name='merchants')
    op.drop_column('merchants', 'postcode')
    # ### end Alembic commands ###
