"""add audit_logs, cash_position_entries, transaction disputes, billing cycle employer-paid fields

Revision ID: e7ccef5c6629
Revises: 468f26d7f9c0
Create Date: 2026-09-06 04:20:19.642855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ccef5c6629'
down_revision = '468f26d7f9c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_position_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('bank_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('billing_cycles', sa.Column('employer_paid_at', sa.DateTime(), nullable=True))
    op.add_column('billing_cycles', sa.Column('employer_paid_reference', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('is_disputed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('transactions', sa.Column('dispute_reason', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('disputed_at', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('dispute_resolved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'dispute_resolved_at')
    op.drop_column('transactions', 'disputed_at')
    op.drop_column('transactions', 'dispute_reason')
    op.drop_column('transactions', 'is_disputed')
    op.drop_column('billing_cycles', 'employer_paid_reference')
    op.drop_column('billing_cycles', 'employer_paid_at')
    op.drop_table('cash_position_entries')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
