"""add employee monthly net pay and spending limit percentage

Revision ID: efcd9fd7faf4
Revises: f4fd48655577
Create Date: 2026-09-09 13:12:39.136375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcd9fd7faf4'
down_revision = 'f4fd48655577'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('monthly_net_pay', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('employee_profiles', sa.Column('spending_limit_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_profiles', 'spending_limit_percentage')
    op.drop_column('employee_profiles', 'monthly_net_pay')
    # ### end Alembic commands ###
