"""add billing cycle expected/received amounts

Revision ID: f4fd48655577
Revises: e7ccef5c6629
Create Date: 2026-09-07 03:40:11.977198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fd48655577'
down_revision = 'e7ccef5c6629'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_cycles', sa.Column('employer_amount_expected', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('billing_cycles', sa.Column('employer_amount_received', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_cycles', 'employer_amount_received')
    op.drop_column('billing_cycles', 'employer_amount_expected')
    # ### end Alembic commands ###
