"""add consent_records table

Revision ID: fe814ecfe4ce
Revises: 794ee3c6206a
Create Date: 2026-09-10 11:21:57.980217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe814ecfe4ce'
down_revision = '794ee3c6206a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('document_version', sa.String(), nullable=False),
    sa.Column('agreed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consent_records')
    # ### end Alembic commands ###
