"""add employer payroll anchor date

Revision ID: ff47a484e6bc
Revises: c3fcff04ff74
Create Date: 2026-09-10 04:24:42.407135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff47a484e6bc'
down_revision = 'c3fcff04ff74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('payroll_anchor_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employers', 'payroll_anchor_date')
    # ### end Alembic commands ###
